services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_web_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - mariadb_default

networks:
  mariadb_default:
    external: true
